[TL-34] Properly handle objects with cycles.
blacklane/kiev-js pull request #18
Opened 2021-08-04 15:35 UTC by giulliano-bueno

2021-08-05 08:28 UTC, AndersonQ requested changes

2021-08-05 08:28 UTC, AndersonQ commented on src/filter.ts
> +  private recursiveFilter(attrs: Object, visited = new Map()) {
It'd be good to have a test to ensure it correctly handles objects with cycles.

2021-08-09 09:24 UTC, bl-rodrigo submitted a review, later dismissed
Add the test case to cover the cycles.

2021-09-07 09:45 UTC, giulliano-bueno commented on src/filter.ts
> +  private recursiveFilter(attrs: Object, visited = new Map()) {
🤔  I had a test in my computer. I will push it ASAP.

2021-09-08 12:15 UTC, bl-rodrigo approved these changes

2021-09-08 12:24 UTC, merged