[VAR-792] Improving Kiev using a logging library underneath
blacklane/kiev-js pull request #6
Opened 2020-10-15 11:03 UTC by rodrigopinto

# What is this PR for?

This is for making Kiev more stable and supports a common logging feature as `logging filtering` based on the log level, as also to add the standards of Blacklane logging. 

The proposed implementation uses https://github.com/pimterry/loglevel underneath to avoid us from _reinvent the weel_.

⚠️ This PR will require a major version bump as it contains breaking changes compared to the current version.

 **what this PR changes?**

- Exposing log methods through a class.
- Enable to initiate the class with standard values as application name and environment.
- Implemented logging filter level through underneath logging library.

TODO:

- [ ] Update the readme to reflect the new version.

### How it looks like from when it gets merged???

How it will be used:

```typescript
import { Kiev } from '@blacklane/kiev-js'

const environment = process.env.NODE_ENV || "development"

// Default level is "warn"
kiev = new Kiev("application-name", environment)

// This won't be logged due to the default level
kiev.debug("Something happening here", { foo: "bar" }) 

// Next line will be logged
kiev.warn("WARN! Look at this", { foo: "bar" }) 

// => {"application":"application-name","environment":"development","level":"ERROR", message: "WARN! Look at this", "timestamp":"2020-10-15T10:51:32.621Z", "foo": "bar"}

// Setting logger to "debug" level
kiev.setLevel("debug")

kiev.debug("FooBar", { fizz: "buzz" }) // Now it will be logged

// => {"application":"application-name","environment":"development","level":"DEBUG", message: "FooBar", "timestamp":"2020-10-15T10:51:32.621Z", "fizz": "buzz"}
```

2020-10-15 13:36 UTC, jairobl commented on src/index.ts
> +class Kiev {
[doubt]
Is there a reason to keep it as Kiev instead of just calling it Logger? As I understand Kiev is just the pattern for the attrs in the log

2020-10-16 16:33 UTC, mariasoulblack submitted a review, later dismissed
LGTM!

2020-10-16 16:33 UTC, mariasoulblack commented on src/index.test.ts
> +import { Kiev, Logger, LogLevel } from '.'
Nice!!! :1st_place_medal:

2020-10-19 09:05 UTC, giulliano-bueno commented
Could specify why it was unstable, please? "This is for making Kiev more stable.."

2020-10-20 07:43 UTC, jsDotCr commented on README.md
> +kiev.setLevel("debug")
Could we use an enum for this `setLevel`?

2020-10-20 07:43 UTC, jsDotCr commented on README.md
> +kiev.debug("FooBar", { fizz: "buzz" }) // Now it will be logged
We should try to be consistent as much as we can with the quotes - since we are using standard.js, we usually stick to  single quotes

2020-10-20 07:43 UTC, jsDotCr commented on src/index.test.ts
> +    loggerInstance = kiev.getLogger()
I would set these in a `beforeEach` hook, so we don't miss any possible issue brought by `setLevel` being set in a test and its value used in another.

2020-10-20 07:43 UTC, jsDotCr commented on src/index.ts
> +  }
I'd rather use a an instance field instead (e.g. [application and environment](https://github.com/blacklane/kiev-js/pull/6/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R26-R27) above), because this getter's job is to wrap the `logger` and that's all.

2020-10-20 07:43 UTC, jsDotCr commented on src/index.ts
> +  protected _buildPayload (
What about marking it as a `private`? This method is only used here internally, no need to be exposed.

2020-10-20 07:43 UTC, jsDotCr commented on src/index.ts
> +   * @param payload [Object] is a JSON object that represents the content of the event.
Watch out for the [JSDoc syntax](https://jsdoc.app/howto-es2015-classes.html) - it's more like `@param {type} argumentName - description`

2020-10-20 07:43 UTC, jsDotCr commented on README.md
> +  ```
For consistency reasons, I'd rather do `npm install` (or `npm clean-install`) + `npm test`; or otherwise `npm i`+ `npm t`, and not a mix.

2020-10-20 09:10 UTC, rodrigopinto commented on src/index.ts
> +class Kiev {
The name of the lib can be anything, but I agree Kiev is not the best. :)

We can move it to Logger for sure, and it makes more sense, but in general, we will call `logger = Kiev.new` only once and then use the variable with the name that was given in the whole application.

2020-10-22 10:46 UTC, jsDotCr approved these changes
💯 👍

2020-10-22 12:58 UTC, AndersonQ requested changes

2020-10-22 12:58 UTC, AndersonQ commented on README.md
> +// Default level is 'warn'
Better to make it info. Most logging libraries have INFO as the default level.

2020-10-22 12:58 UTC, AndersonQ commented on README.md
> +logger.setLevel(LogLevel.DEBUG)
[Suggestion]
Move it up, just after `logger = new Kiev('application-name', environment)` and then, there to add the comment `WARN` is the default log leve.

2020-10-22 12:58 UTC, AndersonQ commented on README.md
> +6. Push to the branch (`git push origin my-new-feature`)
[Suggestion]
We don't need to be so specific, I'd remove these steps.
Also I believe to run the linter is a requirement, so it'd be worth to have it as a step before opening the PR

2020-10-22 12:58 UTC, AndersonQ commented on src/index.ts
> +   */
[Suggestion]
The message field isn't really the _"log event(i.e. request_started, request_finished and etc)."_. It is the message, and might also be _the log event_.

```suggestion
   * @param {String} message is the core information of your log entry. By reading it anyone should understand what the log entry is about.
   * @param {object} payload is a JSON object with all structured fields to be added to the log.
   */
```

2020-10-22 12:58 UTC, AndersonQ commented on src/index.ts
> +   */
[Suggestion]
The message field isn't really the _"log event(i.e. request_started, request_finished and etc)."_. It is the message, and might also be _the log event_.

```suggestion
   * @param {String} message is the core information of your log entry. By reading it anyone should understand what the log entry is about.
   * @param {object} payload is a JSON object with all structured fields to be added to the log.
   */
```

2020-10-22 12:58 UTC, AndersonQ commented on src/index.ts
> +   */
[Suggestion]
The message field isn't really the _"log event(i.e. request_started, request_finished and etc)."_. It is the message, and might also be _the log event_.

```suggestion
   * @param {String} message is the core information of your log entry. By reading it anyone should understand what the log entry is about.
   * @param {object} payload is a JSON object with all structured fields to be added to the log.
   */
```

2020-10-22 12:58 UTC, AndersonQ commented on src/index.ts
> +    logger.error(this._buildPayload(LogLevel.ERROR, message, payload))
[Suggestion]
We should have a `error` parameter as well.
The message field isn't really the _"log event(i.e. request_started, request_finished and etc)."_. It is the message, and might also be _the log event_.

```suggestion
   * @param {String} message is the core information of your log entry. By reading it anyone should understand what the log entry is about.
   * @param {object} payload is a JSON object with all structured fields to be added to the log.
   * @param {String} error is a description of the error.
   */
  public error (message: string, error: string, payload: Object): void {
    logger.error(this._buildPayload(LogLevel.ERROR, message, { error, ...payload }))
```

2020-10-22 12:58 UTC, AndersonQ commented on src/index.ts
> +   */
[Suggestion]
The message field isn't really the _"log event(i.e. request_started, request_finished and etc)."_. It is the message, and might also be _the log event_.

```suggestion
   * @param {String} message is the core information of your log entry. By reading it anyone should understand what the log entry is about.
   * @param {object} payload is a JSON object with all structured fields to be added to the log.
   */
```

2020-10-22 12:58 UTC, AndersonQ commented on src/index.ts
> +  private _buildPayload (
[Suggestion]
Make the description and the name more consistent.

my preferred option
```suggestion
  /**
   * Creates the log entry.
   *
   * @param {String} severity the log level.
   * @param {String} message  is the description of log(i.e. "Lorem ipsum dolor sit amet").
   * @param {Object} payload is a JSON object that represents the content of the event.
   */
  private _buildLog (
```
**OR**

```suggestion
  /**
   * Creates the log structure.
   *
   * @param {String} severity the log level.
   * @param {String} message  is the description of log(i.e. "Lorem ipsum dolor sit amet").
   * @param {Object} payload is a JSON object that represents the content of the event.
   */
  private _buildPayload (
```
```suggestion
  /**
   * Creates the log payload.
   *
   * @param {String} severity the log level.
   * @param {String} message  is the description of log(i.e. "Lorem ipsum dolor sit amet").
   * @param {Object} payload is a JSON object that represents the content of the event.
   */
  private _buildPayload (
```

2020-10-22 13:01 UTC, rodrigopinto commented on src/index.ts
> +   */
you are right, it was actually missing rewrite the doc while adding the message field instead of `event`. Good catch!

2020-10-22 13:06 UTC, AndersonQ commented on src/index.test.ts
> +let kiev: Kiev
[Suggestion]
```suggestion
let logger: Kiev

```

2020-10-22 13:06 UTC, AndersonQ commented on src/index.test.ts
> +describe('kiev', () => {
[Suggestion]

```suggestion
describe('logger', () => {

```

2020-10-22 13:06 UTC, AndersonQ commented on src/index.test.ts
> +    kiev = new Kiev(applicationName, environment)
[Suggestion]
```suggestion
    logger = new Kiev(applicationName, environment)

```

2020-10-22 13:06 UTC, AndersonQ commented on src/index.test.ts
> +      expect(mockLogLevel.setLevel).toHaveBeenCalledWith(LogLevel.WARN)
[Suggestion]
Remove this bit. Why are you testing it twice in the same test?

2020-10-22 13:06 UTC, AndersonQ commented on src/index.test.ts
> +      kiev.setLevel(LogLevel.ERROR)
```suggestion
      logger.setLevel(LogLevel.ERROR)

```

2020-10-22 13:06 UTC, AndersonQ commented on src/index.test.ts
> +    it('logs when current level is equal or greater than the function level', () => {
```suggestion
    it('logs when current level is equal or greater than debug level', () => {

```

2020-10-22 13:06 UTC, AndersonQ commented on src/index.test.ts
> +      kiev.error('There were an event here, see the payload', logPayload)
[Suggestion]
Add an `error` paramter
```suggestion
      kiev.error('There were an event here, see the payload', error, logPayload)

```

2020-10-22 13:08 UTC, AndersonQ commented on src/index.ts
> +class Kiev {
I'd still call it logger, but it's up to you

2020-10-22 13:09 UTC, rodrigopinto commented on src/index.ts
> +class Kiev {
@jairobl said the same. I will rename it!

2020-10-22 13:12 UTC, rodrigopinto commented on src/index.ts
> +class Kiev {
Both of you are right. Let's rename it!

2020-10-22 13:17 UTC, rodrigopinto commented on src/index.test.ts
> +      kiev.error('There were an event here, see the payload', logPayload)
@AndersonQ what you mean by adding the error parameter. It should be part of the `logPayload`, the functions will always have 2 params `message` and the payload to be logged.

2020-10-22 13:27 UTC, rodrigopinto commented on README.md
> +logger.setLevel(LogLevel.DEBUG)
the example is to explain that it will only log based on the current log level. I don't think it makes sense to move it.

2020-10-22 13:28 UTC, rodrigopinto commented on README.md
> +6. Push to the branch (`git push origin my-new-feature`)
Not sure if it is not needed. We can't assume that everyone will know and follow all the steps.

2020-10-26 08:51 UTC, giulliano-bueno approved these changes
LGTM

2020-10-26 08:51 UTC, giulliano-bueno commented on .editorconfg
> -# EditorConfig is awesome: https://EditorConfig.org
What is the problem with our editor config file? Most of the editors have this plugin available and it actually helps us to keep our configuration consistent.

"EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems."

2020-10-26 08:51 UTC, giulliano-bueno commented on README.md
> +[![Build Status](https://travis-ci.com/blacklane/kiev-js.svg?branch=master)](https://travis-ci.com/blacklane/kiev-js)
Nice!

2020-10-26 08:51 UTC, giulliano-bueno commented on README.md
> +npm install @blacklane/kiev-js
Good catch!

2020-10-26 08:51 UTC, giulliano-bueno commented on README.md
> +6. Push to the branch (`git push origin my-new-feature`)
I would keep it this way because it would be noob friendly.

2020-10-26 09:40 UTC, AndersonQ approved these changes

2020-10-26 09:52 UTC, AndersonQ commented on README.md
> +6. Push to the branch (`git push origin my-new-feature`)
You're forgetting this step won't work for the majority of people as they cannot write on the repo.

2020-10-26 14:08 UTC, giulliano-bueno commented on README.md
> +1. Pull the code:
```suggestion
0. Fork this repository
1. Pull the code:
```

2020-10-26 14:09 UTC, giulliano-bueno commented on README.md
> +  git clone git@github.com:blacklane/kiev-js.git
```suggestion
  git clone git@github.com:<your username>/kiev-js.git
```

2020-10-26 14:12 UTC, giulliano-bueno commented on src/index.test.ts
> +      expect(mockLogLevel.setLevel).toHaveBeenCalledWith(LogLevel.ERROR)
What are you testing here?

2020-10-26 14:21 UTC, AndersonQ approved these changes

2020-10-26 15:19 UTC, rodrigopinto commented on README.md
> +1. Pull the code:
This is intended for Blacklane user, not for external users.

2020-10-26 15:19 UTC, rodrigopinto commented on README.md
> +  git clone git@github.com:blacklane/kiev-js.git
ditto.

2020-10-26 15:20 UTC, rodrigopinto commented on src/index.test.ts
> +      expect(mockLogLevel.setLevel).toHaveBeenCalledWith(LogLevel.ERROR)
testing that the wrapped function is being called properly.

2020-10-27 12:50 UTC, merged