Scopped logger
blacklane/kiev-js pull request #8
Opened 2020-11-04 14:36 UTC by AndersonQ

Add fields to be logged by default on every log entry

2020-11-05 09:40 UTC, rodrigopinto requested changes
LGTM left comments related to small changes.

2020-11-05 09:40 UTC, rodrigopinto commented on src/index.ts
> +   * @param fields
need to add the param type and description

2020-11-05 09:40 UTC, rodrigopinto commented on src/index.ts
> +   * @constructor
Is it not a `constructor` is a method that returns a copy instance.

2020-11-05 09:40 UTC, rodrigopinto commented on src/index.ts
> +  public Child (fields?: Object): Logger {
Assigning the `fields?: Object = {}` on the method signature, it removes the need of `fields ?? {}`.

2020-11-05 09:40 UTC, rodrigopinto commented on jest.config
> +}
[doubt]: why do we need this?

2020-11-05 11:30 UTC, AndersonQ commented on jest.config
> +}
**tl;dr**: [tsdx+jest](https://github.com/formium/tsdx#jest), [tsdx#434](https://github.com/formium/tsdx/issues/434#issuecomment-596717920), [tsdx#168](https://github.com/formium/tsdx/issues/168)

@jsDotCr I was looking at the [tsdx docs](https://github.com/formium/tsdx#jest) and it seems to be necessary this file so it can integrate well with IDEs

2020-11-05 11:38 UTC, rodrigopinto approved these changes
🚀

2020-11-05 11:42 UTC, rodrigopinto commented
@AndersonQ Would be nice to update the README with the new possible param on the constructor.

2020-11-05 12:09 UTC, jsDotCr requested changes
I'd try to avoid positional arguments list, favoring a more flexible option/fields object.
Also, there's no example of the `setFields` new function in the readme, it may be worth explaining it too.

2020-11-05 12:09 UTC, jsDotCr commented on README.md
> +logger = new Logger('application-name', environment, { foo: 'foo', bar: 'bar' })
I'm wondering if we could merge the second and third argument, moving towards a unique meta data object instead. At the end of the day, the `environment` is treated like that, it would be more consistent.
To avoid breaking changes, we can always check whether it's a string; if that's the case, we transform it into `{ environment: args[1] }`.

2020-11-05 12:09 UTC, jsDotCr commented on README.md
> +const newLogger = logger.newLogger({ tracking_id: "an tracking ID" })
What about an `extend` rather than `newLogger`? `newLogger` sounds a bit repetitive. [debug](https://www.npmjs.com/package/debug#extend) is for instance using this naming.

2020-11-05 12:09 UTC, jsDotCr commented on src/index.ts
> +   * passed to any of the log methods. If any key was a;ready set, it'll be
```suggestion
   * passed to any of the log methods. If any key was already set, it'll be
```

2020-11-05 12:09 UTC, jsDotCr commented on src/index.ts
> +   * @param {Object} fields to be added to all log entries.
It should be `[fields]` according to [JSDoc's `@param`](https://jsdoc.app/tags-param.html#optional-parameters-and-default-values).

2020-11-05 13:23 UTC, AndersonQ commented on README.md
> +logger = new Logger('application-name', environment, { foo: 'foo', bar: 'bar' })
It makes sense, however it's good to have them explicit as it's required by our logging standard. So I'd let it to a future PR

2020-11-09 09:24 UTC, jsDotCr commented on README.md
> +logger = new Logger('application-name', environment, { foo: 'foo', bar: 'bar' })
By doing it in future it means it will become a breaking change since you would remove the third argument. Fine with it as well, just wondering if that's worth the postponing tho.

2020-11-09 10:42 UTC, rodrigopinto requested changes

2020-11-09 10:42 UTC, rodrigopinto commented on README.md
> +const newLogger = logger.extend({ tracking_id: "an tracking ID" })
👍

2020-11-09 10:42 UTC, rodrigopinto commented on src/index.ts
> +      ...(fields ?? {})
the `fields` should be required on the extend method, as it is the only reason for this method exists.

2020-11-09 14:33 UTC, AndersonQ commented on README.md
> +logger = new Logger('application-name', environment, { foo: 'foo', bar: 'bar' })
I talked with @rodrigopinto and we decided to let it to a later stage

2020-11-09 14:34 UTC, rodrigopinto approved these changes

2020-11-09 15:40 UTC, RaVbaker approved these changes

2020-11-10 08:16 UTC, jsDotCr approved these changes

2020-11-10 09:19 UTC, merged